{
 "title": "Que Benchmarking",
 "description": "Benchmarking dashboard for Que",
 "tags": [ "que" ],
 "time": { "from": "2018-04-27T19:46:39.644Z", "to": "2018-04-27T19:49:39.363Z" },
 "templating": {
  "list": [
   { "name": "env", "label": "env", "query": "benchmark" },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. Workers",
   "type": "singlestat",
   "description": "The number of currently running Que workers",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(que_worker_running_seconds_total{env=\"$env\"}[30s]))"
    }
   ]
  },
  {
   "title": "No. Que Workers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (version) (rate(que_worker_running_seconds_total{env=\"$env\"}[$interval]))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "Rate of Work", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Jobs Worked/s",
   "type": "graph",
   "description": "Rate at which we are working Que jobs, including errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(que_jobs_worked_total{env=\"$env\"}[$interval]))",
     "legendFormat": "job/s"
    },
    {
     "expr": "sum(rate(que_jobs_error_total{env=\"$env\"}[$interval]))",
     "legendFormat": "err/s"
    }
   ]
  },
  { "title": "Utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "% Worker Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(que_worker_job_acquire_seconds_total{env=\"$env\"}[$interval])) / sum(rate(que_worker_running_seconds_total{env=\"$env\"}[$interval]))",
     "legendFormat": "acquire"
    },
    {
     "expr": "sum(rate(que_worker_job_unlock_seconds_total{env=\"$env\"}[$interval])) / sum(rate(que_worker_running_seconds_total{env=\"$env\"}[$interval]))",
     "legendFormat": "unlock"
    },
    {
     "expr": "sum(rate(que_worker_job_exists_seconds_total{env=\"$env\"}[$interval])) / sum(rate(que_worker_running_seconds_total{env=\"$env\"}[$interval]))",
     "legendFormat": "exists"
    },
    {
     "expr": "sum(rate(que_jobs_worked_seconds_total{env=\"$env\"}[$interval])) / sum(rate(que_worker_running_seconds_total{env=\"$env\"}[$interval]))",
     "legendFormat": "work"
    },
    {
     "expr": "sum(rate(que_worker_sleeping_seconds_total{env=\"$env\"}[$interval])) / sum(rate(que_worker_running_seconds_total{env=\"$env\"}[$interval]))",
     "legendFormat": "sleep"
    }
   ]
  }
 ]
}