inherit_gem:
  gc_ruboconfig: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "legacy_spec/**/*"
    - "lib/generators/que/templates/*.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Sequel/IrreversibleMigration:
  Exclude:
    - "**/*_spec.rb"
