name: Publish gem to GitHub package registry

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: gocardless/github-actions/actions/ruby-bundle-install@master
        with:
          known_hosts: ${{ secrets.KNOWN_HOSTS_GITHUB_KEY }}
          robot_ssh_key: ${{ secrets.ROBOT_READONLY_SSH_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Gem
        uses: gocardless/github-actions/actions/publish-internal-gem@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
