name: tests

on:
  push:

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "3.3"]

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_DB: que-test
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      
    env:
      PGDATABASE: que-test
      PGUSER: ubuntu
      PGPASSWORD: password
      PGHOST: localhost

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "${{ matrix.ruby-version }}"
      - name: Run specs
        run: |
          bundle exec rspec