---
name: tests

on:
  push:
    branches:
      - "master"
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  tests:
    strategy:
      matrix:
        ruby-version: ["2.6", "2.7", "3.0", "3.1", "3.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: gocardless/github-actions/proxies/shimataro-ssh-key-action@master
        with:
          key: ${{ secrets.ROBOT_READONLY_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_GITHUB_KEY }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "${{ matrix.ruby-version }}"
      - name: Run tests
        run: bundle exec rspec
      - name: Run rubocop
        run: "bundle exec rubocop --parallel --extra-details --display-style-guidename: test"
